In [1]:
%%capture
%load_ext sql
%sql sqlite:///factbook.db

'Connected: None@factbook.db'

In [2]:
%%sql
SELECT *
  FROM sqlite_master
 WHERE type='table';

Done.

[('table', 'sqlite_sequence', 'sqlite_sequence', 3, 'CREATE TABLE sqlite_sequence(name,seq)'),
 ('table', 'facts', 'facts', 47, 'CREATE TABLE "facts" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "code" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "area" integer, "a ... (4 characters truncated) ... land" integer, "area_water" integer, "population" integer, "population_growth" float, "birth_rate" float, "death_rate" float, "migration_rate" float)')]

In [4]:
%%sql
SELECT *
  FROM facts
 LIMIT 5;

Done.

[(1, 'af', 'Afghanistan', 652230, 652230, 0, 32564342, 2.32, 38.57, 13.89, 1.51),
 (2, 'al', 'Albania', 28748, 27398, 1350, 3029278, 0.3, 12.92, 6.58, 3.3),
 (3, 'ag', 'Algeria', 2381741, 2381741, 0, 39542166, 1.84, 23.67, 4.31, 0.92),
 (4, 'an', 'Andorra', 468, 468, 0, 85580, 0.12, 8.13, 6.96, 0.0),
 (5, 'ao', 'Angola', 1246700, 1246700, 0, 19625353, 2.78, 38.78, 11.49, 0.46)]

In [5]:
%%sql
SELECT MIN(population), MAX(population), 
       MIN(population_growth), MAX(population_growth)
  FROM facts;

Done.

[(0, 7256490011, 0.0, 4.02)]

In [12]:
%%sql
SELECT name, population
  FROM facts
 WHERE population in ((SELECT MIN(population) FROM facts),
                      (SELECT MAX(population) FROM facts)
                     );

Done.

[('Antarctica', 0), ('World', 7256490011)]

In [13]:
%%sql
SELECT MIN(population), MAX(population), 
       MIN(population_growth), MAX(population_growth)
  FROM facts
 WHERE name != 'World';

Done.

[(0, 1367485388, 0.0, 4.02)]

In [16]:
%%sql
SELECT AVG(population), AVG(area)
  FROM facts;

Done.

[(62094928.32231405, 555093.546184739)]

In [19]:
%%sql
SELECT name, population, area
  FROM facts
 WHERE population > (SELECT AVG(population) FROM facts)
       and 
       area < (SELECT AVG(area) FROM facts);

Done.

[('Bangladesh', 168957745, 148460),
 ('Germany', 80854408, 357022),
 ('Japan', 126919659, 377915),
 ('Philippines', 100998376, 300000),
 ('Thailand', 67976405, 513120),
 ('United Kingdom', 64088222, 243610),
 ('Vietnam', 94348835, 331210)]

In [20]:
# What country has the most people?
%%sql
SELECT name, MAX(population)
  FROM facts
 WHERE name != 'World'

Done.

[('China', 1367485388)]

In [21]:
# What country has the highest growth rate?
%%sql
SELECT name, MAX(population_growth)
  FROM facts
 WHERE name != 'World'

Done.

[('South Sudan', 4.02)]

In [22]:
# Which countries have the highest ratios of water to land?
%%sql
SELECT name, MAX(CAST(area_water AS float) / CAST(area_land AS float))
  FROM facts
 WHERE name != 'World'

Done.

[('British Indian Ocean Territory', 905.6666666666666)]

In [24]:
# Which countries have more water than land?
%%sql
SELECT name, area_land, area_water
  FROM facts
 WHERE (area_land - area_water) <= 0;

Done.

[('Holy See (Vatican City)', 0, 0),
 ('British Indian Ocean Territory', 60, 54340),
 ('Virgin Islands', 346, 1564)]

In [41]:
%%sql
SELECT name, birth_rate, death_rate, birth_rate - death_rate AS add_most
  FROM facts
 ORDER BY add_most DESC
 LIMIT 10;

Done.

[('Malawi', 41.56, 8.41, 33.150000000000006),
 ('Uganda', 43.79, 10.69, 33.1),
 ('Niger', 45.45, 12.42, 33.03),
 ('Burundi', 42.01, 9.27, 32.739999999999995),
 ('Mali', 44.99, 12.89, 32.1),
 ('Burkina Faso', 42.03, 11.72, 30.310000000000002),
 ('Zambia', 42.13, 12.67, 29.46),
 ('Ethiopia', 37.27, 8.19, 29.080000000000005),
 ('South Sudan', 36.91, 8.18, 28.729999999999997),
 ('Tanzania', 36.39, 8.0, 28.39)]

In [42]:
%%sql
SELECT name, birth_rate, death_rate, death_rate - birth_rate
  FROM facts
 ORDER BY death_rate - birth_rate DESC;

Done.

[('Bulgaria', 8.92, 14.44, 5.52),
 ('Serbia', 9.08, 13.66, 4.58),
 ('Latvia', 10.0, 14.31, 4.3100000000000005),
 ('Lithuania', 10.1, 14.27, 4.17),
 ('Ukraine', 10.72, 14.46, 3.74),
 ('Hungary', 9.16, 12.73, 3.5700000000000003),
 ('Germany', 8.47, 11.42, 2.9499999999999993),
 ('Slovenia', 8.42, 11.37, 2.9499999999999993),
 ('Romania', 9.14, 11.9, 2.76),
 ('Croatia', 9.45, 12.18, 2.7300000000000004),
 ('Belarus', 10.7, 13.36, 2.66),
 ('Monaco', 6.65, 9.24, 2.59),
 ('Greece', 8.66, 11.09, 2.4299999999999997),
 ('Saint Pierre and Miquelon', 7.42, 9.72, 2.3000000000000007),
 ('Russia', 11.6, 13.69, 2.09),
 ('Estonia', 10.51, 12.4, 1.8900000000000006),
 ('Portugal', 9.27, 11.02, 1.75),
 ('Japan', 7.93, 9.51, 1.58),
 ('Italy', 8.74, 10.19, 1.4499999999999993),
 ('Bosnia and Herzegovina', 8.87, 9.75, 0.8800000000000008),
 ('Czech Republic', 9.63, 10.34, 0.7099999999999991),
 ('Moldova', 12.0, 12.59, 0.5899999999999999),
 ('Poland', 9.74, 10.19, 0.4499999999999993),
 ('Austria', 9.41, 9.42, 0.009999999999999787),
 ('European Union', 10.2, 10.2, 0.0),
 ('Denmark', 10.27, 10.25, -0.019999999999999574),
 ('Slovakia', 9.91, 9.74, -0.16999999999999993),
 ('San Marino', 8.63, 8.45, -0.1800000000000015),
 ('Spain', 9.64, 9.04, -0.6000000000000014),
 ('Finland', 10.72, 9.83, -0.8900000000000006),
 ('Montenegro', 10.42, 9.43, -0.9900000000000002),
 ('Isle of Man', 11.1, 10.06, -1.0399999999999991),
 ('Guernsey', 9.84, 8.78, -1.0600000000000005),
 ('Malta', 10.18, 9.09, -1.0899999999999999),
 ('Andorra', 8.13, 6.96, -1.1700000000000008),
 ('Taiwan', 8.47, 7.11, -1.3600000000000003),
 ('Korea, South', 8.19, 6.75, -1.4399999999999995),
 ('Virgin Islands', 10.31, 8.54, -1.7700000000000014),
 ('Belgium', 11.41, 9.63, -1.7799999999999994),
 ('Canada', 10.28, 8.42, -1.8599999999999994),
 ('Georgia', 12.74, 10.82, -1.92),
 ('Hong Kong', 9.23, 7.07, -2.16),
 ('Netherlands', 10.83, 8.66, -2.17),
 ('Cuba', 9.9, 7.72, -2.1800000000000006),
 ('Puerto Rico', 10.86, 8.67, -2.1899999999999995),
 ('Switzerland', 10.5, 8.13, -2.369999999999999),
 ('Saint Helena, Ascension, and Tristan da Cunha', 9.88, 7.44, -2.4400000000000004),
 ('Macedonia', 11.55, 9.08, -2.4700000000000006),
 ('Sweden', 11.99, 9.4, -2.59),
 ('United Kingdom', 12.17, 9.35, -2.8200000000000003),
 ('Palau', 11.05, 7.99, -3.0600000000000005),
 ('Bermuda', 11.33, 8.23, -3.0999999999999996),
 ('France', 12.38, 9.16, -3.2200000000000006),
 ('Liechtenstein', 10.45, 7.12, -3.329999999999999),
 ('Thailand', 11.19, 7.8, -3.3899999999999997),
 ('Barbados', 11.87, 8.44, -3.4299999999999997),
 ('Uruguay', 13.07, 9.45, -3.620000000000001),
 ('Norway', 12.14, 8.12, -4.020000000000001),
 ('Luxembourg', 11.37, 7.24, -4.129999999999999),
 ('Jersey', 11.91, 7.68, -4.23),
 ('Armenia', 13.61, 9.34, -4.27),
 ('United States', 12.49, 8.15, -4.34),
 ('Aruba', 12.56, 8.18, -4.380000000000001),
 ('Macau', 8.88, 4.22, -4.660000000000001),
 ('Cyprus', 11.41, 6.62, -4.79),
 ('Singapore', 8.27, 3.43, -4.84),
 ('Trinidad and Tobago', 13.46, 8.56, -4.9),
 ('China', 12.49, 7.53, -4.96),
 ('Montserrat', 11.26, 6.3, -4.96),
 ('Australia', 12.15, 7.14, -5.010000000000001),
 ('Faroe Islands', 13.77, 8.71, -5.059999999999999),
 ('Korea, North', 14.52, 9.21, -5.309999999999999),
 ('Curacao', 13.8, 8.2, -5.600000000000001),
 ('Gibraltar', 14.08, 8.37, -5.710000000000001),
 ('Namibia', 19.8, 13.91, -5.890000000000001),
 ('British Virgin Islands', 10.91, 4.99, -5.92),
 ('New Zealand', 13.33, 7.36, -5.97),
 ('Greenland', 14.48, 8.49, -5.99),
 ('Falkland Islands (Islas Malvinas)', 10.9, 4.9, -6.0),
 ('Saint Lucia', 13.7, 7.42, -6.279999999999999),
 ('Cook Islands', 14.33, 8.03, -6.300000000000001),
 ('Albania', 12.92, 6.58, -6.34),
 ('Mauritius', 13.29, 6.91, -6.379999999999999),
 ('Saint Vincent and the Grenadines', 13.57, 7.18, -6.390000000000001),
 ('Saint Kitts and Nevis', 13.5, 7.09, -6.41),
 ('Cayman Islands', 12.11, 5.53, -6.579999999999999),
 ('Seychelles', 14.19, 6.89, -7.3),
 ('Dominica', 15.41, 7.91, -7.5),
 ('Botswana', 20.96, 13.39, -7.57),
 ('Iceland', 13.91, 6.28, -7.63),
 ('Chile', 13.83, 6.0, -7.83),
 ('Brazil', 14.46, 6.58, -7.880000000000001),
 ('Grenada', 16.03, 8.08, -7.950000000000001),
 ('Anguilla', 12.67, 4.57, -8.1),
 ('Guyana', 15.59, 7.32, -8.27),
 ('Qatar', 9.84, 1.53, -8.31),
 ('Ireland', 14.84, 6.48, -8.36),
 ('Wallis and Futuna', 13.45, 5.06, -8.39),
 ('Bahamas, The', 15.5, 7.05, -8.45),
 ('Sint Maarten', 13.0, 4.51, -8.49),
 ('Argentina', 16.64, 7.33, -9.31),
 ('Azerbaijan', 16.64, 7.07, -9.57),
 ('Lebanon', 14.59, 4.88, -9.71),
 ('Sri Lanka', 15.85, 6.11, -9.739999999999998),
 ('New Caledonia', 15.33, 5.52, -9.81),
 ('Vietnam', 15.96, 5.93, -10.030000000000001),
 ('Antigua and Barbuda', 15.85, 5.69, -10.16),
 ('French Polynesia', 15.22, 5.02, -10.200000000000001),
 ('Suriname', 16.34, 6.13, -10.21),
 ('Indonesia', 16.72, 6.37, -10.349999999999998),
 ('Burma', 18.39, 7.96, -10.43),
 ('Turkey', 16.33, 5.88, -10.45),
 ('Lesotho', 25.47, 14.89, -10.579999999999998),
 ('Tunisia', 16.64, 5.98, -10.66),
 ('El Salvador', 16.46, 5.69, -10.77),
 ('World', 18.6, 7.8, -10.8),
 ('South Africa', 20.75, 9.91, -10.84),
 ('Kazakhstan', 19.15, 8.21, -10.939999999999998),
 ('Bahrain', 13.66, 2.69, -10.97),
 ('Colombia', 16.47, 5.4, -11.069999999999999),
 ('Bhutan', 17.78, 6.69, -11.09),
 ('Swaziland', 24.67, 13.56, -11.110000000000001),
 ('Costa Rica', 15.91, 4.55, -11.36),
 ('Jamaica', 18.16, 6.7, -11.46),
 ('Paraguay', 16.37, 4.68, -11.690000000000001),
 ('Uzbekistan', 17.0, 5.3, -11.7),
 ('Guam', 16.82, 5.12, -11.7),
 ('Maldives', 15.75, 3.89, -11.86),
 ('Iran', 17.99, 5.94, -12.049999999999997),
 ('India', 19.55, 7.32, -12.23),
 ('Peru', 18.28, 6.01, -12.270000000000001),
 ('Nicaragua', 18.03, 5.08, -12.950000000000001),
 ('Turks and Caicos Islands', 16.13, 3.1, -13.03),
 ('Turkmenistan', 19.4, 6.13, -13.27),
 ('Israel', 18.48, 5.15, -13.33),
 ('Fiji', 19.43, 6.04, -13.39),
 ('Morocco', 18.2, 4.81, -13.39),
 ('Ecuador', 18.51, 5.06, -13.450000000000003),
 ('United Arab Emirates', 15.43, 1.97, -13.459999999999999),
 ('Panama', 18.32, 4.81, -13.510000000000002),
 ('Mexico', 18.78, 5.26, -13.520000000000001),
 ('Brunei', 17.32, 3.52, -13.8),
 ('Venezuela', 19.16, 5.31, -13.850000000000001),
 ('Mongolia', 20.25, 6.35, -13.9),
 ('Nepal', 20.64, 6.56, -14.080000000000002),
 ('Dominican Republic', 18.73, 4.55, -14.18),
 ('Cabo Verde', 20.33, 6.11, -14.219999999999999),
 ('Kiribati', 21.46, 7.12, -14.34),
 ('Libya', 18.03, 3.58, -14.450000000000001),
 ('Haiti', 22.31, 7.83, -14.479999999999999),
 ('Northern Mariana Islands', 18.32, 3.71, -14.61),
 ('Malaysia', 19.71, 5.03, -14.68),
 ('Tuvalu', 23.74, 8.74, -14.999999999999998),
 ('Saudi Arabia', 18.51, 3.33, -15.180000000000001),
 ('Bangladesh', 21.14, 5.61, -15.530000000000001),
 ('Samoa', 20.87, 5.32, -15.55),
 ('Djibouti', 23.65, 7.73, -15.919999999999998),
 ('Pakistan', 22.58, 6.49, -16.089999999999996),
 ('Cambodia', 23.83, 7.68, -16.15),
 ('Bolivia', 22.76, 6.52, -16.240000000000002),
 ('Micronesia, Federated States of', 20.54, 4.23, -16.31),
 ('Kyrgyzstan', 22.98, 6.65, -16.33),
 ('Laos', 24.25, 7.63, -16.62),
 ('Kuwait', 19.91, 2.18, -17.73),
 ('Papua New Guinea', 24.38, 6.53, -17.849999999999998),
 ('Honduras', 23.14, 5.17, -17.97),
 ('Egypt', 22.9, 4.77, -18.13),
 ('American Samoa', 22.89, 4.75, -18.14),
 ('Tonga', 23.0, 4.85, -18.15),
 ('Philippines', 24.27, 6.11, -18.16),
 ('Syria', 22.17, 4.0, -18.17),
 ('Tajikistan', 24.38, 6.18, -18.2),
 ('Belize', 24.68, 5.97, -18.71),
 ('Guinea-Bissau', 33.38, 14.33, -19.050000000000004),
 ('Nauru', 24.95, 5.87, -19.08),
 ("Cote d'Ivoire", 28.67, 9.55, -19.12),
 ('Algeria', 23.67, 4.31, -19.360000000000003),
 ('West Bank', 22.99, 3.5, -19.49),
 ('Kenya', 26.4, 6.89, -19.509999999999998),
 ('Guatemala', 24.89, 4.77, -20.12),
 ('Comoros', 27.84, 7.57, -20.27),
 ('Vanuatu', 25.04, 4.09, -20.95),
 ('Oman', 24.44, 3.36, -21.080000000000002),
 ('Central African Republic', 35.08, 13.8, -21.279999999999998),
 ('Gabon', 34.49, 13.12, -21.370000000000005),
 ('Marshall Islands', 25.6, 4.21, -21.39),
 ('Sudan', 29.19, 7.66, -21.53),
 ('Jordan', 25.37, 3.79, -21.580000000000002),
 ('Western Sahara', 30.24, 8.34, -21.9),
 ('Solomon Islands', 25.77, 3.85, -21.919999999999998),
 ('Zimbabwe', 32.26, 10.13, -22.129999999999995),
 ('Chad', 36.6, 14.28, -22.32),
 ('Eritrea', 30.0, 7.52, -22.48),
 ('Mauritania', 31.34, 8.2, -23.14),
 ('Yemen', 29.98, 6.28, -23.7),
 ('Gambia, The', 30.86, 7.15, -23.71),
 ('Ghana', 31.09, 7.22, -23.87),
 ('Afghanistan', 38.57, 13.89, -24.68),
 ('Liberia', 34.41, 9.69, -24.72),
 ('Nigeria', 37.64, 12.9, -24.740000000000002),
 ('Rwanda', 33.75, 8.96, -24.79),
 ('Congo, Democratic Republic of the', 34.88, 10.07, -24.810000000000002),
 ('Equatorial Guinea', 33.31, 8.19, -25.120000000000005),
 ('Madagascar', 32.61, 6.81, -25.8),
 ('Congo, Republic of the', 35.85, 10.0, -25.85),
 ('Cameroon', 36.17, 10.11, -26.060000000000002),
 ('Senegal', 34.52, 8.46, -26.060000000000002),
 ('Sierra Leone', 37.03, 10.81, -26.22),
 ('Guinea', 35.74, 9.46, -26.28),
 ('Mozambique', 38.58, 12.1, -26.479999999999997),
 ('Somalia', 40.45, 13.62, -26.830000000000005),
 ('Togo', 34.13, 7.26, -26.870000000000005),
 ('Sao Tome and Principe', 34.23, 7.24, -26.989999999999995),
 ('Angola', 38.78, 11.49, -27.29),
 ('Iraq', 31.45, 3.77, -27.68),
 ('Benin', 36.02, 8.21, -27.810000000000002),
 ('Timor-Leste', 34.16, 6.1, -28.059999999999995),
 ('Gaza Strip', 31.11, 3.04, -28.07),
 ('Tanzania', 36.39, 8.0, -28.39),
 ('South Sudan', 36.91, 8.18, -28.729999999999997),
 ('Ethiopia', 37.27, 8.19, -29.080000000000005),
 ('Zambia', 42.13, 12.67, -29.46),
 ('Burkina Faso', 42.03, 11.72, -30.310000000000002),
 ('Mali', 44.99, 12.89, -32.1),
 ('Burundi', 42.01, 9.27, -32.739999999999995),
 ('Niger', 45.45, 12.42, -33.03),
 ('Uganda', 43.79, 10.69, -33.1),
 ('Malawi', 41.56, 8.41, -33.150000000000006),
 ('Kosovo', None, None, None),
 ('Holy See (Vatican City)', None, None, None),
 ('Ashmore and Cartier Islands', None, None, None),
 ('Christmas Island', None, None, None),
 ('Cocos (Keeling) Islands', None, None, None),
 ('Coral Sea Islands', None, None, None),
 ('Heard Island and McDonald Islands', None, None, None),
 ('Norfolk Island', None, None, None),
 ('Clipperton Island', None, None, None),
 ('French Southern and Antarctic Lands', None, None, None),
 ('Saint Barthelemy', None, None, None),
 ('Saint Martin', None, None, None),
 ('Niue', None, None, None),
 ('Tokelau', None, None, None),
 ('Bouvet Island', None, None, None),
 ('Jan Mayen', None, None, None),
 ('Svalbard', None, None, None),
 ('Akrotiri', None, None, None),
 ('British Indian Ocean Territory', None, None, None),
 ('Dhekelia', None, None, None),
 ('Pitcairn Islands', None, None, None),
 ('South Georgia and South Sandwich Islands', None, None, None),
 ('Navassa Island', None, None, None),
 ('Wake Island', None, None, None),
 ('United States Pacific Island Wildlife Refuges', None, None, None),
 ('Antarctica', None, None, None),
 ('Paracel Islands', None, None, None),
 ('Spratly Islands', None, None, None),
 ('Arctic Ocean', None, None, None),
 ('Atlantic Ocean', None, None, None),
 ('Indian Ocean', None, None, None),
 ('Pacific Ocean', None, None, None),
 ('Southern Ocean', None, None, None)]

In [43]:
%%sql
SELECT name, population, area, population / area
  FROM facts
 ORDER BY population / area DESC;

Done.

[('Macau', 592731, 28, 21168),
 ('Monaco', 30535, 2, 15267),
 ('Singapore', 5674472, 697, 8141),
 ('Hong Kong', 7141106, 1108, 6445),
 ('Gaza Strip', 1869055, 360, 5191),
 ('Gibraltar', 29258, 6, 4876),
 ('Bahrain', 1346613, 760, 1771),
 ('Maldives', 393253, 298, 1319),
 ('Malta', 413965, 316, 1310),
 ('Bermuda', 70196, 54, 1299),
 ('Sint Maarten', 39689, 34, 1167),
 ('Bangladesh', 168957745, 148460, 1138),
 ('Guernsey', 66080, 78, 847),
 ('Jersey', 97294, 116, 838),
 ('Barbados', 290604, 430, 675),
 ('Mauritius', 1339827, 2040, 656),
 ('Taiwan', 23415126, 35980, 650),
 ('Aruba', 112162, 180, 623),
 ('Lebanon', 6184701, 10400, 594),
 ('Saint Martin', 31754, 54, 588),
 ('San Marino', 33020, 61, 541),
 ('Korea, South', 49115196, 99720, 492),
 ('Rwanda', 12661733, 26338, 480),
 ('West Bank', 2785366, 5860, 475),
 ('Nauru', 9540, 21, 454),
 ('Tuvalu', 10869, 26, 418),
 ('Netherlands', 16947904, 41543, 407),
 ('Marshall Islands', 72191, 181, 398),
 ('Israel', 8049314, 20770, 387),
 ('Burundi', 10742276, 27830, 385),
 ('India', 1251695584, 3287263, 380),
 ('Belgium', 11323973, 30528, 370),
 ('Haiti', 10110019, 27750, 364),
 ('Comoros', 780971, 2235, 349),
 ('Philippines', 100998376, 300000, 336),
 ('Sri Lanka', 22053488, 65610, 336),
 ('Japan', 126919659, 377915, 335),
 ('Curacao', 148406, 444, 334),
 ('Grenada', 110694, 344, 321),
 ('Guam', 161785, 544, 297),
 ('El Salvador', 6141350, 21041, 291),
 ('Vietnam', 94348835, 331210, 284),
 ('American Samoa', 54343, 199, 273),
 ('Jamaica', 2950210, 10991, 268),
 ('Saint Lucia', 163922, 616, 266),
 ('Saint Vincent and the Grenadines', 102627, 389, 263),
 ('United Kingdom', 64088222, 243610, 263),
 ('Puerto Rico', 3598357, 13791, 260),
 ('Pakistan', 199085847, 796095, 250),
 ('Trinidad and Tobago', 1222363, 5128, 238),
 ('Liechtenstein', 37624, 160, 235),
 ('Germany', 80854408, 357022, 226),
 ('British Virgin Islands', 33454, 151, 221),
 ('Luxembourg', 570252, 2586, 220),
 ('Dominican Republic', 10478756, 48670, 215),
 ('Nepal', 31551305, 147181, 214),
 ('Cayman Islands', 56092, 264, 212),
 ('Antigua and Barbuda', 92436, 442, 209),
 ('Korea, North', 24983205, 120538, 207),
 ('Italy', 61855120, 301340, 205),
 ('Seychelles', 92430, 455, 203),
 ('Sao Tome and Principe', 194006, 964, 201),
 ('Saint Kitts and Nevis', 51936, 261, 198),
 ('Nigeria', 181562056, 923768, 196),
 ('Switzerland', 8121830, 41277, 196),
 ('Qatar', 2194817, 11586, 189),
 ('Andorra', 85580, 468, 182),
 ('Anguilla', 16418, 91, 180),
 ('Gambia, The', 1967709, 11300, 174),
 ('Kosovo', 1870981, 10887, 171),
 ('Kuwait', 2788534, 17818, 156),
 ('Uganda', 37101745, 241038, 153),
 ('Isle of Man', 87545, 572, 153),
 ('Malawi', 17964697, 118484, 151),
 ('Micronesia, Federated States of', 105216, 702, 149),
 ('China', 1367485388, 9596960, 142),
 ('Tonga', 106501, 747, 142),
 ('Guatemala', 14918999, 108889, 137),
 ('Cabo Verde', 545993, 4033, 135),
 ('Czech Republic', 10644842, 78867, 134),
 ('Indonesia', 255993674, 1904569, 134),
 ('Thailand', 67976405, 513120, 132),
 ('Togo', 7552318, 56785, 132),
 ('Kiribati', 105711, 811, 130),
 ('Denmark', 5581503, 43094, 129),
 ('Cyprus', 1189197, 9251, 128),
 ('Akrotiri', 15700, 123, 127),
 ('Poland', 38562189, 312685, 123),
 ('Dhekelia', 15700, 130, 120),
 ('European Union', 513949445, 4324782, 118),
 ('Portugal', 10825309, 92090, 117),
 ('Azerbaijan', 9780780, 86600, 112),
 ('Northern Mariana Islands', 52344, 464, 112),
 ('Slovakia', 5445027, 49035, 111),
 ('Tokelau', 1337, 12, 111),
 ('Ghana', 26327649, 238533, 110),
 ('Wallis and Futuna', 15613, 142, 109),
 ('Hungary', 9897541, 93028, 106),
 ('Albania', 3029278, 28748, 105),
 ('Moldova', 3546847, 33851, 104),
 ('Austria', 8665550, 83871, 103),
 ('France', 66553766, 643801, 103),
 ('Armenia', 3056382, 29743, 102),
 ('Turkey', 79414269, 783562, 101),
 ('Cuba', 11031433, 110860, 99),
 ('Dominica', 73607, 751, 98),
 ('Slovenia', 1983412, 20273, 97),
 ('Spain', 48146134, 505370, 95),
 ('Costa Rica', 4814144, 51100, 94),
 ('Benin', 10448647, 112622, 92),
 ('Malaysia', 30513848, 329847, 92),
 ('Serbia', 7176794, 77474, 92),
 ('Syria', 17064854, 185180, 92),
 ('Ethiopia', 99465819, 1104300, 90),
 ('Jordan', 8117564, 89342, 90),
 ('Romania', 21666350, 238391, 90),
 ('Egypt', 88487396, 1001450, 88),
 ('Cambodia', 15708756, 181035, 86),
 ('Iraq', 37056169, 438317, 84),
 ('Burma', 56320206, 676578, 83),
 ('Swaziland', 1435613, 17364, 82),
 ('Timor-Leste', 1231116, 14874, 82),
 ('Greece', 10775643, 131957, 81),
 ('Macedonia', 2096015, 25713, 81),
 ('Sierra Leone', 5879098, 71740, 81),
 ('Kenya', 45925301, 580367, 79),
 ('Croatia', 4464844, 56594, 78),
 ('Honduras', 8746673, 112090, 78),
 ('Bosnia and Herzegovina', 3867055, 51197, 75),
 ('Brunei', 429646, 5765, 74),
 ('Morocco', 33322699, 446550, 74),
 ('Ukraine', 44429471, 603550, 73),
 ("Cote d'Ivoire", 23295302, 322463, 72),
 ('Senegal', 13975834, 196722, 71),
 ('Georgia', 4931226, 69700, 70),
 ('Burkina Faso', 18931686, 274200, 69),
 ('Ireland', 4892305, 70273, 69),
 ('Samoa', 197773, 2831, 69),
 ('United Arab Emirates', 5779760, 83600, 69),
 ('Tunisia', 11037225, 163610, 67),
 ('French Polynesia', 282703, 4167, 67),
 ('Uzbekistan', 29199942, 447400, 65),
 ('Bulgaria', 7186893, 110879, 64),
 ('Lesotho', 1947701, 30355, 64),
 ('Mexico', 121736809, 1964375, 61),
 ('Norfolk Island', 2210, 36, 61),
 ('Tajikistan', 8191958, 144100, 56),
 ('Ecuador', 15868396, 283561, 55),
 ('Eritrea', 6527689, 117600, 55),
 ('Virgin Islands', 103574, 1910, 54),
 ('Tanzania', 51045882, 947300, 53),
 ('Turks and Caicos Islands', 50280, 948, 53),
 ('Montserrat', 5241, 102, 51),
 ('Yemen', 26737317, 527968, 50),
 ('Afghanistan', 32564342, 652230, 49),
 ('Cameroon', 23739218, 475440, 49),
 ('Fiji', 909389, 18274, 49),
 ('Iran', 81824270, 1648195, 49),
 ('Panama', 3657024, 75420, 48),
 ('Guinea', 11780162, 245857, 47),
 ('Guinea-Bissau', 1726170, 36125, 47),
 ('Belarus', 9589689, 207600, 46),
 ('Montenegro', 647073, 13812, 46),
 ('Palau', 21265, 459, 46),
 ('Nicaragua', 5907881, 130370, 45),
 ('Lithuania', 2884433, 65300, 44),
 ('South Africa', 53675563, 1219090, 44),
 ('Cocos (Keeling) Islands', 596, 14, 42),
 ('Colombia', 46736728, 1138910, 41),
 ('Cook Islands', 9838, 236, 41),
 ('Madagascar', 23812681, 587041, 40),
 ('Liberia', 4195666, 111369, 37),
 ('Zimbabwe', 14229541, 390757, 36),
 ('Faroe Islands', 50196, 1393, 36),
 ('Djibouti', 828324, 23200, 35),
 ('Congo, Democratic Republic of the', 79375136, 2344858, 33),
 ('United States', 321368864, 9826675, 32),
 ('Venezuela', 29275460, 912050, 32),
 ('Mozambique', 25303113, 799380, 31),
 ('Latvia', 1986705, 64589, 30),
 ('Laos', 6911544, 236800, 29),
 ('Kyrgyzstan', 5664939, 199951, 28),
 ('Estonia', 1265420, 45228, 27),
 ('Equatorial Guinea', 740743, 28051, 26),
 ('Saint Helena, Ascension, and Tristan da Cunha', 7795, 308, 25),
 ('Bahamas, The', 324597, 13880, 23),
 ('Brazil', 204259812, 8515770, 23),
 ('Chile', 17508260, 756102, 23),
 ('Peru', 30444999, 1285216, 23),
 ('Saint Pierre and Miquelon', 5657, 242, 23),
 ('Vanuatu', 272264, 12189, 22),
 ('Solomon Islands', 622469, 28896, 21),
 ('Sweden', 9801616, 450295, 21),
 ('Zambia', 15066266, 752618, 20),
 ('Bhutan', 741919, 38394, 19),
 ('Sudan', 36108853, 1861484, 19),
 ('South Sudan', 12042910, 644329, 18),
 ('Uruguay', 3341893, 176215, 18),
 ('Algeria', 39542166, 2381741, 16),
 ('Finland', 5476922, 338145, 16),
 ('New Zealand', 4438393, 267710, 16),
 ('Norway', 5207689, 323802, 16),
 ('Paraguay', 6783272, 406752, 16),
 ('Somalia', 10616380, 637657, 16),
 ('Angola', 19625353, 1246700, 15),
 ('Argentina', 43431886, 2780400, 15),
 ('Belize', 347369, 22966, 15),
 ('Papua New Guinea', 6672429, 462840, 14),
 ('New Caledonia', 271615, 18575, 14),
 ('Congo, Republic of the', 4755097, 342000, 13),
 ('Mali', 16955536, 1240192, 13),
 ('Saudi Arabia', 27752316, 2149690, 12),
 ('Christmas Island', 1530, 135, 11),
 ('Oman', 3286936, 309500, 10),
 ('Turkmenistan', 5231422, 488100, 10),
 ('Bolivia', 10800882, 1098581, 9),
 ('Central African Republic', 5391539, 622984, 8),
 ('Russia', 142423773, 17098242, 8),
 ('Gabon', 1705336, 267667, 6),
 ('Kazakhstan', 18157122, 2724900, 6),
 ('Niue', 1190, 260, 4),
 ('Botswana', 2182719, 581730, 3),
 ('Canada', 35099836, 9984670, 3),
 ('Guyana', 735222, 214969, 3),
 ('Iceland', 331918, 103000, 3),
 ('Libya', 6411776, 1759540, 3),
 ('Mauritania', 3596702, 1030700, 3),
 ('Suriname', 579633, 163820, 3),
 ('Australia', 22751014, 7741220, 2),
 ('Namibia', 2212307, 824292, 2),
 ('Western Sahara', 570866, 266000, 2),
 ('Mongolia', 2992908, 1564116, 1),
 ('Pitcairn Islands', 48, 47, 1),
 ('Greenland', 57733, 2166086, 0),
 ('Svalbard', 1872, 62045, 0),
 ('Falkland Islands (Islas Malvinas)', 3361, 12173, 0),
 ('Chad', 11631456, None, None),
 ('Niger', 18045729, None, None),
 ('Holy See (Vatican City)', 842, 0, None),
 ('Ashmore and Cartier Islands', None, 5, None),
 ('Coral Sea Islands', None, 3, None),
 ('Heard Island and McDonald Islands', None, 412, None),
 ('Clipperton Island', None, 6, None),
 ('French Southern and Antarctic Lands', None, None, None),
 ('Saint Barthelemy', 7237, None, None),
 ('Bouvet Island', None, 49, None),
 ('Jan Mayen', None, 377, None),
 ('British Indian Ocean Territory', None, 54400, None),
 ('South Georgia and South Sandwich Islands', None, 3903, None),
 ('Navassa Island', None, 5, None),
 ('Wake Island', None, 6, None),
 ('United States Pacific Island Wildlife Refuges', None, None, None),
 ('Antarctica', 0, None, None),
 ('Paracel Islands', None, 7, None),
 ('Spratly Islands', None, 5, None),
 ('Arctic Ocean', None, None, None),
 ('Atlantic Ocean', None, None, None),
 ('Indian Ocean', None, None, None),
 ('Pacific Ocean', None, None, None),
 ('Southern Ocean', None, None, None),
 ('World', 7256490011, None, None)]